### ISSUE TITLE
Plugin does not work after installation in 2015-08-10a "Detritus"

### ISSUE THREAD

**Issue by meisterT** [zioth/dokuwiki_fastwiki#16]
I did install the plugin in dokuwiki version: Release 2015-08-10a "Detritus"
It shows up in the configuration settings, but nothing else happens, i.e. section editing opens the usual editor and not yours. Probably I missed one step to make it work.
Does it depend on other plugins?

**Comment by zioth** [comment]
Did you check the sectionedit option in the configuration? If you give me the URL of your wiki, I might be able to figure out what's wrong.

**Comment by meisterT** [comment]
Sorry, the wiki is behind a firewall. And yes, the sectionedit option is checked.

Is there anything in the HTML header I can check that the plugin is loaded such as JS includes?

**Comment by zioth** [comment]
Try opening the JavaScript console in your browser and typing:
JSINFO.fastwiki

That will tell you what settings the plugin thinks are on.

What browser version are you using?

**Comment by meisterT** [comment]
That looks good:
Object { secedit: 1, preview: 1, fastpages: 1, save: 0, fastshow: 0, fastshow_same_ns: 1, fastshow_include: "", fastshow_exclude: "", ...

However, there is a JS error in the console:
ReferenceError: doPost is not defined js.php:24:123912

Is this maybe related?

**Comment by zioth** [comment]
That's a very strange error, given the way doPost is defined. What browser are you using version?

**Comment by meisterT** [comment]
I am using Firefox/iceweasel 38 on debian. The doPost error is not visible in chromium. However, the section edit feature also does not work.
I also tried to disable other (useless) plugins with no change.

**Comment by zioth** [comment]
Sorry for the delay. I've updated the plugin. I'm not sure it will fix your problem, but it's worth a try!

**Comment by PeterBurner** [comment]
You can fix the "ReferenceError: doPost is not defined" by defining the function before you call it ;)
[fix](https://github.com/zioth/dokuwiki_fastwiki/files/94730/pagecache.zip)

**Comment by zioth** [comment]
Sounds like a Firefox bug. When you declare functions using the "function x()" syntax, they shouldn't have to be declared before they're called. Maybe the Firefox bug happens when the function is declared inside a closure.

Anyway, it's an easy fix, and thanks for pointing it out!

**Comment by zioth** [comment]
meisterT, all known issues in this area have been fixed. Let me know if it works now, and I'll close the ticket.

**Comment by q2apro** [comment]
Have the same problem on latest Chrome. Installed latest dokuwiki on localhost, installed fastwiki afterwards. 

Result: nothing changes

Theme: dokuwiki default

No error message in the web console. 

Console shows with `JSINFO.fastwiki`: 

     Object {secedit: 1, preview: 1, fastpages: 1, save: 0, fastshow: 0…}fastpages: 1fastshow: 0fastshow_exclude: ""fastshow_include: ""fastshow_same_ns: 1locktime: 840preload: falsepreload_batchsize: falsepreload_head: "====47hsjwycv782nwncv8b920m8bv72jmdm3929bno3b3===="preload_per_page: falsepreview: 1save: 0secedit: 1templatename: "dokuwiki"text_btn_show: "Show page"usedraft: 1__proto__: Object

How to solve the "invisible" problem? :)

**Comment by zioth** [comment]
I recently fixed another FireFox bug which could have caused this issue. If you're still using the plugin, would you mind taking a look? Thanks!

**Comment by zioth** [comment]
Since there haven't been any further comments on this topic, I'm closing the issue.
