### ISSUE TITLE
Firefox and IE problems

### ISSUE THREAD

**Issue by PeterBurner** [zioth/dokuwiki_fastwiki#17]
* Inline Editing doesn't work under Firefox and IE
* DokuWiki Editor Toolbar disappeared under Firefox and IE

**Comment by PeterBurner** [comment]
You can fix this by escaping the fourth hyphen in line 15 of history.js
if (id.match(/^[a-zA-Z0-9_-:]+$/))	-->	if (id.match(/^[a-zA-Z0-9_\\-:]+$/))

**Comment by PeterBurner** [comment]
[fix](https://github.com/zioth/dokuwiki_fastwiki/files/94757/history.zip)

**Comment by zioth** [comment]
Good catch. Thanks. I'm surprised that didn't break in all browsers, since it should exclude anything that has an underscore, dash or colon. Maybe Webkit has a bug in its regex parser which made this expression work.
