### ISSUE TITLE
Fastedit broken in Dokuwiki version 'Elanor of Tsort'

### ISSUE THREAD

**Issue by digitalcohesion** [zioth/dokuwiki_fastwiki#19]
When clicking edit the screen darkens and the a progress bar comes up but doesn't go away.

If I hit the preview button on the darkened screen behind the progress bar everything seems to work normally.

I'm using Eleanor of Tsort and the Bootstrap3 template with Yeti theme from Bootswatch. On my system the progress bar isn't needed at all I don't think. The page change happens instantly and otherwise I think the inline edit and preview would work fine.

**Comment by zioth** [comment]
What's "Eleanor of Tsort?" I've tested with Bootstrap3, I think, but not with any of the themes.

**Comment by digitalcohesion** [comment]
It's the latest version of Dokuwiki. Previous version was called Detritus I believe.

**Comment by zioth** [comment]
Oh. I'd missed the new release. Thanks for letting me know. I'll have to install it and test. It could be that some new incompatibility was introduced.

**Comment by zioth** [comment]
Fixed. If you notice any other problems with Elanor of Tsort, let me know!
