### ISSUE TITLE
NS_ERROR_FAILURE on Firefox, works in Chrome

### ISSUE THREAD

**Issue by micgro42** [zioth/dokuwiki_fastwiki#20]
Hi,

I still have the issue described in issue #19 in the current version of your plugin (Head of master branch). However it only appears in Firefox, Chromium on the other hand works as expected.

I'm using Firefox 47.0 and Chromium 51.0.2704.106 .

The stacktrace in the javascript console is as follows:
```
DWsetSelection()
_focusEdit()
m_actionEffects.edit()
cb()
_sendPartial/<()
jQuery.Callbacks/fire()
jQuery.Callbacks/self.fireWith()
done()
.send/callback/<()
```

**Comment by zioth** [comment]
It works fine for me in FireFox 47. It could be a timing issue. I've added exception handling and a re-try, since textarea.focus() can fail in some situations.

Could you update, try again, and let me know if any warnings show up in the console, and whether the bug is fixed? Thanks.

**Comment by micgro42** [comment]
Yes, that fixed it for me! Thank you :smiley: 

PS: There is some output from your change in the Javascript-console:
```
DWsetSelection failed. Trying again in 500ms.
```

**Comment by zioth** [comment]
Great. The fact that you got that message and not another means the fix worked.
