### ISSUE TITLE
Sidebar links not clickable on start page

### ISSUE THREAD

**Issue by digitalcohesion** [zioth/dokuwiki_fastwiki#21]
I loaded the latest version after the progress bar fix, and that seems to work fine now. However, now I notice that my sidebar doesn't work on the primary start page. If I load a page in a namespace, the sidebar functions properly and I can click the links.

Looking at the generated page, I can't see any difference in the html, so my guess is there is some javascript being overridden somewhere. The links are the same, the css class is the same in the link, so I'm not quite sure what the difference is.

This is a bit unfortunate as everyone that uses our wiki begins on the start page and uses the sidebar to navigate.

**Comment by zioth** [comment]
The fastwiki plugin overrides a lot of javascript. If your sidebar is broken and you need it to work right away, try turning off some of the fastwiki settings.

I'd also be happy to debug the issue, if you give me access to your wiki and turn off JS compression.

**Comment by digitalcohesion** [comment]
I couldn't find a setting that made any difference. I did also realize that it's not just the sidebar, it's also the navbar. Maybe that helps give a better idea of what's wrong?

The default home links at the top don't work either when I'm on the start page. The links in the menu bar widgets work though.

I'll keep looking into this later when I have more time and if I don't come up with anything more concrete I'll see if I can get access set up for you.

**Comment by zioth** [comment]
Yeah. Since I don't know what your wiki looks like, it's hard to say what could have gone wrong with the sidebar or navbar.

When the "fastpages" setting is turned on, all wiki action links on the page (?do=whatever), and all forms with a "do" field, are intercepted. It's possible that your wiki is set up in a way I didn't take into account. The fact that edit now works makes this seem strange.

Only the experimental settings mess with non-action links, so I'm not sure why your entire nav bar would be broken.

What template are you using?

**Comment by digitalcohesion** [comment]
It's the Bootstrap3 with Yeti Bootswatch theme.

Here's an example from an existing public site of what it looks like.

http://www.lotar.altervista.org/dokuwiki/start <http://www.lotar.altervista.org/dokuwiki/start>

I do have the .htaccess url stuff on so my links look similar. 

/start, /namespace/start, etc.

- Kevin

**Comment by zioth** [comment]
Hm... There are a lot of non-action links in the sidebar and nav bar in that example, so I'm not sure how fastwiki could have caused the problem.

I think I'd need to see your site, or if it includes a lot of private content, a clone of your site with the content removed. You could even zip up the content-light clone and send it to me if you want. Just make sure to change the admin login first. :)

**Comment by digitalcohesion** [comment]
I found more info. The problem seems to be related to the current page and the linked pages in the sidebar having the same name. So in my wiki my start page is named start and all the links are to pages named start in different namespaces. If I link to a page not named start in the different namespace it seems to work OK. Hopefully that will make sense to you and you can fix it easily. If not then I can send you a link to a test wiki setup to demonstrate the problem.

**Comment by zioth** [comment]
That's actually really useful information. I have an idea of what might be causing the bug.

**Comment by zioth** [comment]
Ok. I think this only happens when the link has the same name as your page, and your page's ID is not in a namespace. So :a and :b:a will cause a problem, but :b:a and :c:a won't.

**Comment by zioth** [comment]
Fixed
