### ISSUE TITLE
imgpaste doesn't seem to work once fastwiki is installed

### ISSUE THREAD

**Issue by alexbevi** [zioth/dokuwiki_fastwiki#22]
Not sure if there's anything to be done on your end, but thought I'd report regardless.

Running on 2016-06-26a of Dokuwiki

**Comment by zioth** [comment]
I've added a pull request to imgpaste to add fastwiki support. If it's accepted, you'll be able to update that plugin to fix the issue.

**Comment by zioth** [comment]
The pull request has been merged. Sorry it took over a year, @alexbevi !
