### ISSUE TITLE
Inline Section Editing in combination with the EditTable doesn't work

### ISSUE THREAD

**Issue by bgroenendal** [zioth/dokuwiki_fastwiki#23]
I love this plugin, it really does make DokuWiki work allot better and especially faster. However I've had to disable the inline section editing because one of our most used plugins isn't working correctly with it.

The EditTable plugin, https://www.dokuwiki.org/plugin:edittable , behaves different from the regular plugins. I can see two behaviors that are incorrect:

**1. Edit an existing table inline (inline section edit enabled).**

You click the edit button under the table. Then it loads the plugin (inline) but it only shows the save, cancel, etc. buttons but not the actual EditTable plugin.

![schermafbeelding 2016-09-16 om 10 16 05](https://cloud.githubusercontent.com/assets/14563606/18579594/ece2f01c-7bf6-11e6-9150-71714afd5417.png)

**2. Create a new table during inline section editing or full page editing**

You edit a section or the full page (inline). Then you click the EditTable button in the formatting toolbar for creating a new table. You will be brought to a new page where you can only create the table, this is normal behavior for this plugin. When your done you click save and your brought back to the regular editor. However, you are now no longer editing inline. The editor is the default edit style of DokuWiki (not inline but new page for editing).

**Summary**
Issue number 2 doesn't really bother me, I think it's fine if that's how this works together.
Issue number 1 should however do the same as number 2. It should bring you to a new page for editing the table.

**Workaround**
At the moment I can only make these two plugins work together when I disable the Inline Section Editing.

**Solution?**
I think it will be hard to make the EditTable plugin "edit" inline, that would be annoying to maintain (at least, that's my assumption).

However, would it be possible to exclude the EditTable plugin from the inline section edit behavior? That would allow for the Inline Section Edit feature to be enabled along with the EditTable plugin.

**Comment by zioth** [comment]
I'm glad you like the plugin, and thanks for the detailed bug report! I've fixed it so only the default edit button tries to use inline editing. I can't fully test my fix though, because some other plugin is conflicting with it (edittable creates a global class called Map, which some other plugin must be messing with).
