### ISSUE TITLE
fast section editing fails with include plugin

### ISSUE THREAD

**Issue by rottaran** [zioth/dokuwiki_fastwiki#28]
I have a wiki page that consists of multiple sections included via the include plugin into another wiki page. This shows section edit buttons for each of the included sections. Without the fastwiki section-edit feature I can edit these included sections. When enabling the fastwiki's section-edit, I get the editor window but of the wrong page, i.e. not the included page.

As it seems, the include plugin does not produce edit buttons that point to the included page. Instead it does some magic when the editor is opened in order to redirect the editing to the contents of the included page.

**Comment by zioth** [comment]
I think this is fixed now, along with issue #31. If it's not, feel free to reopen.
