### ISSUE TITLE
Support action links of other pages

### ISSUE THREAD

**Issue by jaller94** [zioth/dokuwiki_fastwiki#29]
**Steps to reproduce:**
1. Install fastwiki
2. Create a page with action links to other pages. For example:
```
  * [[playground:playground?do=backlink]]
  * [[sidebar?do=edit]]
```

**Expected behaviour:** The actions (e.g. backlink and edit) get called on the page of refered to in the link.
**Actual behaviour:** The actions get called on the page you're currently on.

**Additional notes:** Following a link to another page should be added to the BrowserHistory. I would also include the action since a user intentionally constructed a link this way. Those non-selfrefering action links don't appear in a standard DokuWiki according to my knowledge.

**Comment by zioth** [comment]
You closed this issue. Does that mean it's not really happening?

I agree that following a link should add it to BrowserHistory. I thought that part was working for normal pages, but I've had some trouble with History around pushing pages with actions (?do=edit etc). I haven't had much time to work on this recently, so the bug's lingered.

**Comment by jaller94** [comment]
Sorry, my mistake. The referenced issue still exists and has not been resolved. The detection for those non-selfrefering action links does not work.

If I had to take a guess it is this line that causes this issue [this line](https://github.com/zioth/dokuwiki_fastwiki/blob/master/script.js#L77).

**Comment by zioth** [comment]
That's funny. I forgot about this ticket, and then reported it myself as issue #31. Anyway, it's fixed.

**Comment by zioth** [comment]
Sorry it took so long!
