### ISSUE TITLE
Clicking on Tag consisting non-latin symbol returns empty result

### ISSUE THREAD

**Issue by DenisVS** [zioth/dokuwiki_fastwiki#30]
On each page, where is tags by [tag plugin](https://www.dokuwiki.org/plugin:tag), clicking on tag, consisting the non-latin (urlencoded) symbol returns empty result.
The structure of url is:

`http://site.com/tag:%D0%BD%D0%B0%D0%BF%D0%B8%D1%82%D0%BE%D0%BA?do=showtag&tag=%D0%BD%D0%B0%D0%BF%D0%B8%D1%82%D0%BE%D0%BA`

In the ajax query will be seen urlencoded symbols too

```
do=showtag
tag=Ð½Ð°Ð¿Ð¸ÑÐ¾Ðº
partial=1
```

**Comment by zioth** [comment]
Fixed. I took showtag out of the "fast" list, until I can fix it properly.
