### ISSUE TITLE
Weird Conflict: Fastwiki + Nice URLs + Dokubook Template result in missing background color

### ISSUE THREAD

**Issue by bannisdale** [zioth/dokuwiki_fastwiki#39]
So I have a rather specific problem: I use the Dokubook template and the Fastwiki plugin which usually work well together. But if I also activate "Nice URLs" in the config, some background color in the edit window is missing.

That's how it normally looks (Dokuwiki + Nice URLs, Fastwiki disabled):

![image](https://user-images.githubusercontent.com/42511384/93899982-2cfa2700-fcf5-11ea-9c3b-ef1f889a3f05.png)

And this is what it looks like with the previous configuration but Fastwiki plugin enabled:

![image](https://user-images.githubusercontent.com/42511384/93900132-531fc700-fcf5-11ea-8aaf-7c3cb9ce5a83.png)

Both examples are accessed via the normal "Edit this page" button. Also, besides the obvious background color, there is also the missing trace as well as the other spacing.

Weirdly enough, if I just use Fastwiki and the Dokubook template with normal URLs, everything looks just fine, too. So I'm pretty lost on the question of who is to blame.

I'm aware that this is a pretty specific configuration, but I would still like to make it work, if that's possible. :-)

Thanks in advance!

**Comment by zioth** [comment]
Is your wiki public? If so, and you give me edit access to a page, I may be able to figure out whether this is fastwiki's fault.

**Comment by bannisdale** [comment]
I've set up a public fresh install with installing/activating the beforementioned configuration.

http://dorgan.grrmpf.de/test/

**Comment by zioth** [comment]
The page structure of your template is different from what fastwiki expects, which could be what results in the gray background. What is your "Nice URLs" setting? `.htaccess` or `DokuWiki internal`?

Either Fastwiki is the culprit, or I can add a little code to make it compatible with your template (which I've done for several other templates). The missing trace may not be easily fixable. Unlike every other template I've seen, yours puts the trace inside the edit area, which means Fastwiki would need specialized code to handle that case for your template specifically.

**Comment by bannisdale** [comment]
I've tried both versions of nice urls, but it's currently set to DokuWiki internal.

I think I don't care much about the trace not showing up, as long as the rest looks like it didn't run into a css error. :D

**Comment by zioth** [comment]
Fixed. I didn't add the trace, but your background color and other styles should now be correct.

**Comment by bannisdale** [comment]
I can confirm it's fixed. Thanks for the fast response!

Out of curiosity: I can understand how the interaction between the template and the plugin might've been messed up, but how was this interacting with the Nice URLs setting? :D

**Comment by zioth** [comment]
The problem was that `dokubook` used a `<main>` tag instead of a `<div>`, and applied styles directly to `main` (which is generally bad practice). So that was pretty easy to fix once I understood the problem.

"Nice URLs" may have been involved because a some of Fastwiki's features work differently or not at all when that setting is off.
