### ISSUE TITLE
Link Wizard Bug

### ISSUE THREAD

**Issue by ross41** [zioth/dokuwiki_fastwiki#41]
For some unknown reason, this plugin breaks my Link Wizard. Whenever I click on it, no matter what template I use, Link Wizard's window opens up either at the top of a page, or a way down, beneath all possible content. Sometimes it seems like the Wizard doesn't open at all.

I believe I don't have any plugins that directly interfere with Fastwiki.

_Version_: Hogfather.

**Comment by zioth** [comment]
What's Link Wizard? A dokuwiki plugin? Browser plugin?

**Comment by ross41** [comment]
That's a default DW tool (I assume); a toolbar button that opens up a little window where you can visually create a link to wiki's internal page. The button literally says "Internal Link [L]" when you place a cursor over it.

**Comment by zioth** [comment]
Ah, thanks. I'll take a look, but I probably won't have time this week or next. In the mean time, please let me know what template you're using, and if it's not too much trouble, which plugins. If you're able to give me access to edit at least one page on your wiki, that would be helpful too.

**Comment by ross41** [comment]
> let me know what template you're using
Vector, but it doesn't matter. I've tried several, including the default one, end the problem seems to be persistent.
> and if it's not too much trouble, which plugins
Not problem at all, [here](https://pastebin.com/UP2w2eUJ). But I must warn you, I've tried disabling **all** non-bundled plugins and the Wizard still didn't work properly.
> If you're able to give me access to edit at least one page on your wiki, that would be helpful too.
That I cannot do, sorry. My wiki is at the LAN and there's no way anyone from the outside can access it.

**Comment by ross41** [comment]
Any luck working on this issue?

**Comment by zioth** [comment]
> Any luck working on this issue?

Sorry. Haven't had time yet. Feel free to keep bugging me! :)

**Comment by ross41** [comment]
Any luck yet? I can work without your plugin, but it's not the same... 

As promised, I'm bugging you once in a ~fortnight :D

**Comment by zioth** [comment]
I've partially fixed the issue. The link wizard should now open in a more reasonable place, but it won't be perfect. This is because of a bug in Dokiwiki itself, which I've reported: https://github.com/splitbrain/dokuwiki/issues/3466

**Comment by ross41** [comment]
Oh, thank you!
