### ISSUE TITLE
Editing the text under Chrome (Android) does not work

### ISSUE THREAD

**Issue by update-freak** [zioth/dokuwiki_fastwiki#44]
Hello developers,

customizing the text in DokuWiki in Chrome on an Android device does not work, i.e. it does not time the text to be edited like on Windows.

**Comment by zioth** [comment]
Not sure what you mean by "customizing the text" or "time the text." Could you give steps to reproduce the issue?

**Comment by update-freak** [comment]
Yes, sure.

Image 1 (1.jpg): Initial situation in the Chrome browser in Android 8.0.0
Image 2 (2 - without Plugin.jpg): Without Plugin: Appearance after clicking "Edit".
Image 3 (3 - with Plugin.jpg): With Plugin: Appearance after clicking "Edit". The edit window does not open. Instead, the text is hidden. 

![1](https://user-images.githubusercontent.com/40196995/128204292-026a1482-0f9f-4359-9d65-1349602ce253.jpg)
![2 - without Plugin](https://user-images.githubusercontent.com/40196995/128204303-aaeb1621-4cd0-4002-abfd-8c45bf84dc91.jpg)
![3 - with Plugin](https://user-images.githubusercontent.com/40196995/128204312-56ffae74-9efe-4cd4-ae18-9d2016a71871.jpg)

Other plugins that are installed:
- Bootstrap3 Template
- bpmnio
- Bootstrap Wrapper Plugin
- Changes Plugin
- DW2PDF Plugin
- MathJax Plugin
- Move Plugin
- Video Share Plugin
- upgrade Plugin

Release 2020-07-29 "Hogfather"
Template v2021-03-11 (stable/20210311)

**Comment by zioth** [comment]
Thanks! I'll try to get to this soon, but I have a lot going on, so feel free to bug me if I forget about it.

**Comment by update-freak** [comment]
Have you had time to look at this problem?

**Comment by zioth** [comment]
Sorry. Not yet. Keep bugging me! :)

**Comment by update-freak** [comment]
no problem. Is there any news on this problem?

**Comment by update-freak** [comment]
@zioth Have you checked the issue?

**Comment by zioth** [comment]
Sorry. Not yet. I may not be able to get to it until October, but I'll see.

**Comment by update-freak** [comment]
Any news on that issue?

**Comment by zioth** [comment]
Fixed! Sorry for the long delay. I finally had a moment to look at it.

**Comment by zioth** [comment]
My fix caused some other problems. Now there's a better fix. :)
